#version: '2.1'
#services:
 #   mysql:
#        build: ./mysql
#        command: --default-authentication-plugin=mysql_native_password
#        restart: always
#        environment:
#            MYSQL_ROOT_PASSWORD: example
#        healthcheck:
#            test: "exit 0"

version: '3.6'

services:
  mysql1:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "127.0.0.1:4000:3306"
    volumes:
      -   type: bind
          source: ./mysql
          target: /docker-entrypoint-initdb.d
    expose:
      - "3306"
    networks:
      - app-network
    healthcheck:
          test: "exit 0"
  myapp:
    build: .
    depends_on:
      mysql1:
          condition: service_healthy
    ports:
      - "127.0.0.1:5000:5000"
    expose:
      - "5000"
    links:
      - mysql1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge